#!/usr/bin/env bash

#nonmutatable globals

#OTHER
TRANSCOMPILER_TOOL='unilang-transcompiler';
UNILANG_FILE_EXTENSION='UniLang';

###################
# SIMHOST RELATED #
###################

#PATHS
FULL_PATH_TO_ROOT_OF_ACTUAL_REPO='/home/malko/Desktop/work-related/fresh'
FULL_PATH_TO_UNICODE_ROOT='/home/malko/Desktop/UniLang-rewrite/code'
LOCAL_SOURCE_ROOT='SimHost/UH72A_VME/Src'
LOCAL_TEST_ROOT='SimHost/Tests/Unit_Tests'

#derived
FULL_PATH_TO_CODE_ROOT="$FULL_PATH_TO_ROOT_OF_ACTUAL_REPO""/""$LOCAL_SOURCE_ROOT""/"
FULL_PATH_TO_TEST_ROOT="$FULL_PATH_TO_ROOT_OF_ACTUAL_REPO""/""$LOCAL_TEST_ROOT""/"

###########################
# VXWORKS WRAPPER RELATED #
###########################

FULL_PATH_TO_VXWORKS_WRAPPERS='/home/malko/Desktop/work-related/external-unit-test-deps/For_Linux/VxWorks_Wrappers'
