#!/usr/bin/env bash

#nonmutatable globals

#PATHS
FULL_PATH_TO_ROOT_OF_ACTUAL_REPO='/home/malko/Desktop/work-related/fresh'
FULL_PATH_TO_UNICODE_ROOT='/home/malko/Desktop/UniLang-rewrite/code'
LOCAL_SOURCE_ROOT='SimHost/UH72A VME/Src'
LOCAL_TEST_ROOT='SimHost/Tests/Unit_Tests'

#derived
FULL_PATH_TO_CODE_ROOT="$FULL_PATH_TO_ROOT_OF_ACTUAL_REPO""/""$LOCAL_SOURCE_ROOT""/"
FULL_PATH_TO_TEST_ROOT="$FULL_PATH_TO_ROOT_OF_ACTUAL_REPO""/""$LOCAL_TEST_ROOT""/"

#OTHER
TRANSCOMPILER_TOOL='unilang-transcompiler';
UNILANG_FILE_EXTENSION='Unilang';
