#!/usr/bin/env bash

function UniLang-Transform(){
  #name of UniLang file / where to place in repo / where to place class wrapper

  cd Data_Structures;
  Transfer-Object-Bad-Bools "vector" "Components/Electrical/Generic" "Components/Electrical/Generic"
  cd -;
  
  #Utilities
  cd Other/Utilities;
  #Transfer-Global "time_utilities" "Shared/ffs"
  #Transfer-Global "date_utilities" "Shared/ffs"
  cd -;

  #Time related
  cd Systems/Time;
  #Transfer-Global "month" "Components/Time"
  #Transfer-Object-Bad-Bools "date_time" "Components/Time" "Components/Time"
  #Transfer-Object-Bad-Bools "millisecond_timer" "Components/Time" "Components/Time"
  #Transfer-Object-Bad-Bools "simulation_clock" "Components/Time" "Components/Time"
  cd -;

  #Electrical Generic related
  cd Systems/Electrical/generic;
  #Transfer-Object-Bad-Bools "junction" "Components/Electrical/Generic" "Components/Electrical/Generic"
  #Transfer-Object-Bad-Bools "node" "Components/Electrical/Generic" "Components/Electrical/Generic"
  #Transfer-Global "node_type" "Components/Electrical/Generic"
  #Transfer-Object-Bad-Bools "electrical_graph" "Components/Electrical/Generic" "Components/Electrical/Generic"
  #Transfer-Object-Bad-Bools "path" "Components/Electrical/Generic" "Components/Electrical/Generic"
  #Transfer-Object-Bad-Bools "paths" "Components/Electrical/Generic" "Components/Electrical/Generic"
  #Transfer-Global "electrical_config" "Components/Electrical/Generic"
  cd -;

  #Electrical Specific related
  cd Systems/Electrical/specific;
  #Transfer-Object-Bad-Bools "after_junction_box" "Components/Electrical/Specific" "Components/Electrical/Specific"
  #Transfer-Object-Bad-Bools "battery_box" "Components/Electrical/Specific" "Components/Electrical/Specific"
  #Transfer-Object-Bad-Bools "diode_box" "Components/Electrical/Specific" "Components/Electrical/Specific"
  #Transfer-Object-Bad-Bools "distribution_box" "Components/Electrical/Specific" "Components/Electrical/Specific"
  #Transfer-Object-Bad-Bools "overhead_panel" "Components/Electrical/Specific" "Components/Electrical/Specific"
  #Transfer-Object-Bad-Bools "D_C_power_system" "Components/Electrical/Specific" "Components/Electrical/Specific"
  cd -;

  #Electrical Manager related
  cd Systems/Electrical/manager;
  #Transfer-Global "electrical_input_setter" "SystemManagers/Electrical"
  #Transfer-Global "electrical_malfunction_applier" "SystemManagers/Electrical"
  #Transfer-Global "electrical_updater" "SystemManagers/Electrical"
  cd -;
  
  #Electrical components
  cd Systems/Electrical/components;
  #Transfer-Object-Bad-Bools "battery" "Components/Electrical" "Components/Electrical"
  #Transfer-Global "battery_chemistry" "Components/Electrical/Battery" "Components/Electrical/Battery"
  cd -;
  

  #Other stuff
  cd Other;
  #Transfer-Global "ffs_const" "Shared/ffs"
  cd -;
  
  #Connection stuff
  cd Connections/J2;
  #Transfer-Global "j2_communication" "Connections/UDP/";
  #Transfer-Global "j2_message_types" "Connections/UDP/J2Communication/";
  cd -;
  
  cd Components;
  #Transfer-Object-Bad-Bools "tri_state_switch" "Components/Generic/Controls" "Components/Generic/Controls";
  #Transfer-Global "tri_state" "Components/Generic/Controls/TriStateSwitch";
  cd -;
  
  cd Connections/Configs;
  #Transfer-Global "Gls_communication_config" "Connections/UDP/GLInstruments";
  #Transfer-Global "Ios_communication_config" "Connections/UDP/IOS";
  #Transfer-Global "J2_communication_config" "Connections/UDP/J2Communication";
  #Transfer-Global "Sep_communication_config" "Connections/UDP/SEP";
  #Transfer-Global "Srns_communication_config" "Connections/UDP/SRNS";
  #Transfer-Global "Arc231_communication_config" "Connections/UDP/Arc231";
  #Transfer-Global "aural_communication_config" "Connections/UDP/Aural";
  #Transfer-Global "bug_eye_communication_config" "Connections/UDP/BugEye";
  #Transfer-Global "ctrl_loader_communication_config" "Connections/UDP/ControlLoader";
  #Transfer-Global "garmin_communication_config" "Connections/UDP/Garmin430";
  #Transfer-Global "motion_seats_communication_config" "Connections/UDP/MotionSeats";
  cd -;
  
  cd Concurrency;
  #Transfer-Global "time_thread" "Concurrency";
  cd -;
  
  cd Other/DynamicDebug;
  #Transfer-Global "dynamic_debug_configuration" "Connections/UDP/DynamicDebug";
  #Transfer-Global "dynamic_debug_type" "Connections/UDP/DynamicDebug";
  #Transfer-Global "dynamic_debug" "Connections/UDP/DynamicDebug";
  #Transfer-Global "dynamic_debug_message" "Connections/UDP/DynamicDebug";
  #Transfer-Global "dynamic_debug_sender" "Connections/UDP/DynamicDebug";
  cd -;
  
}
