#!/usr/bin/env bash

#nonmutatable globals

#TOOL NAMES
#programs that are run in our transcompiler code formatting automation process.
TRANSCOMPILER_TOOL='unilang-transcompiler';

#I'd like to transition to clang-3.9
#clang-3.8 is broken in terms of brackets
CLANG_FORMAT_TOOL='clang-format-3.9';


#The expected file extension of our UniLang code
UNILANG_FILE_EXTENSION='UniLang';

###################
# SIMHOST RELATED #
###################

#PATHS
#relevant for transferring created files, from one directory to another
FULL_PATH_TO_ROOT_OF_ACTUAL_REPO='/home/malko/Desktop/work-related/fresh'
FULL_PATH_TO_UNICODE_ROOT='/home/malko/Desktop/UniLang-rewrite/code'
LOCAL_SOURCE_ROOT='SimHost/UH72A_VME/Src'
LOCAL_TEST_ROOT='SimHost/Tests/Unit_Tests'

#derived
FULL_PATH_TO_CODE_ROOT="$FULL_PATH_TO_ROOT_OF_ACTUAL_REPO""/""$LOCAL_SOURCE_ROOT""/"
FULL_PATH_TO_TEST_ROOT="$FULL_PATH_TO_ROOT_OF_ACTUAL_REPO""/""$LOCAL_TEST_ROOT""/"

###########################
# VXWORKS WRAPPER RELATED #
###########################
#Used for the static analyzers
FULL_PATH_TO_VXWORKS_WRAPPERS='/home/malko/Desktop/work-related/external-unit-test-deps/For_Linux/VxWorks_Wrappers'
